### ISSUE TITLE
Crash observed

### ISSUE THREAD

**Issue by sergei** [joabakk/signalk-polar#57]
```
TypeError: Cannot read property 'polarSpeeds' of undefined
    at update.values.reduce (/Users/sergei/github/forks/signalk-polar/index.js:550:67)
    at Array.reduce (<anonymous>)
    at delta.updates.forEach.update (/Users/sergei/github/forks/signalk-polar/index.js:408:38)
    at Array.forEach (<anonymous>)
    at FullSignalK.handleDelta (/Users/sergei/github/forks/signalk-polar/index.js:402:21)
    at FullSignalK.emit (events.js:187:15)
    at FullSignalK.addDelta (/Users/sergei/github/forks/signalk-server/node_modules/@signalk/signalk-schema/dist/fullsignalk.js:52:8)
    at doProcess (/Users/sergei/github/forks/signalk-server/lib/deltachain.js:10:13)
    at DeltaChain.process (/Users/sergei/github/forks/signalk-server/lib/deltachain.js:6:16)
    at Function.Server.app.handleMessage (/Users/sergei/github/forks/signalk-server/lib/index.js:172:28)
    at Simple.result.pipeElements.(anonymous function).on.msg (/Users/sergei/github/forks/signalk-server/lib/pipedproviders.js:36:17)
    at Simple.emit (events.js:187:15)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Simple.Readable.push (_stream_readable.js:219:10)
    at Simple.Transform.push (_stream_transform.js:151:32)
TypeError: Cannot read property 'polarSpeeds' of undefined
 ```

**Comment by sergei** [comment]
That seems to be happening here:
```
                  var storedSpeed = mainPolarData[windSpeedIndex].polarSpeeds[windAngleIndex]
```
in my case the TWS is 12.08718 and mainPolarData.length is 3 
I guess 3 is derived from maxWind==15 and twsInterval==4 
So if TWS is greater than 12 the crash is imminent

**Comment by joabakk** [comment]
Thank you for reporting this. You are correct this was why. Should work now. Otherwise, please reopen with further details
